# Generated by Django 4.2.7 on 2023-11-21 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='t',
        ),
        migrations.AddField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='path',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='small_path',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
