# Generated by Django 4.2.7 on 2023-11-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_picture_t_picture_date_picture_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='checksum',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
