# Generated by Django 4.2.7 on 2023-11-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_picture_checksum_alter_picture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='checksum',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
