# Generated by Django 4.2.7 on 2023-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_picture_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
